### ISSUE TITLE
Error: Cannot load Gundo with newest version of Vim (Vim 7.4 Patches 1-663)

### ISSUE THREAD

**Issue by phongvcao** [simnalamburt/vim-mundo#8] opened 2015-03-20 21:05 UTC
Hi,

I was trying to open Gundo today and here were the error messages it gave me:
```
"__Gundo_Preview__" [New File]
Error detected while processing function gundo#GundoToggle..<SNR>183_GundoToggle..<SNR>183_GundoOpen..<SNR>183_GundoPyt
hon:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/phongvcao/.vim/bundle/vim-mundo/autoload/gundo.py", line 631, in GundoRenderGraph
    result = generate(walk_nodes(dag), asciiedges, nodesData.current(), verbose, len(header)+1, first_visible_line, las
t_visible_line)
  File "/home/phongvcao/.vim/bundle/vim-mundo/autoload/gundo.py", line 304, in generate
    preview_diff = nodesData.preview_diff(node.parent, node,False,show_inine_diff)
  File "/home/phongvcao/.vim/bundle/vim-mundo/autoload/gundo.py", line 582, in preview_diff
    self.diffs[key] = one_line_diff_str('\n'.join(before_lines),'\n'.join(after_lines),maxwidth)
  File "/home/phongvcao/.vim/bundle/vim-mundo/autoload/gundo.py", line 54, in one_line_diff_str
    if len(result) + len(v) > mx:
TypeError: unorderable types: int() > str()
line    4:
E319: Sorry, the command is not available in this version: python GundoRenderPreview()
Press ENTER or type command to continue
```
I am using Vim 7.4 Patches 1-663 with +python3 support on Arch Linux. It seems that there have been some changes to Vim which conflict with Gundo. Also, it seems that Gundo cannot pickup the fact that I am running Vim +python3 instead of +python. The s:has_supported_python was reset to 0 everytime I launch Gundo... I hope there would be a fix soon because many users will be affected by these bugs.

**Comment by dsummersl** [comment] 2015-03-20 21:35
Looks like the issue is that we don't support python 3. I'll look into fixing that this weekend. Thanks for the stack trace!

**Comment by phongvcao** [comment] 2015-03-20 22:14
@dsummersl I was actually using simnalamburt/vim-mundo instead of the original Gundo which has the variable g:gundo_prefer_python3 set to 1. Thus, Gundo (or vim-mundo) should have run just fine.

**Comment by simnalamburt** [comment] 2015-03-21 03:05
Acknowledged, looks like python3 support have been dropped accidentally during the recent breaking change of vim-mundo source code. Will be fixed in 2 day.

**Comment by simnalamburt** [comment] 2015-03-22 13:34
@phongvcao I've fixed that issue but it seems there's more to fix. How did you get the stack trace?

**Closed** 2015-03-22 14:30 UTC

**Comment by simnalamburt** [comment] 2015-03-22 14:35
@phongvcao Thanks for your report, please let us know if there's any other problem using vim-mundo :+1:

**Comment by phongvcao** [comment] 2015-03-22 15:06
@simnalamburt thanks guys it is working perfectly now... :dancers:
