### ISSUE TITLE
Very very slow

### ISSUE THREAD

**Issue by eyalk5** [simnalamburt/vim-mundo#91] opened 2020-02-16 16:35 UTC
Hi, I am on latest version of mundo , neovim 0.5 .

When I tried to open it,  it hanged for more than 10 minutes, and it still hasn't opened. 
I believe eventually, it would be opened as I remember delays of 5 minutes. 
The file is text file 43 kb. 

I did made a lot of changes along the time. 
I do have some "memory pressure" in my OS, as appeared in activity monitor (like close to 16gb of ram usage, probably need to go to page file ). But other things work pretty well.   

So, it is not justified. Can something be optimizied out?

**Comment by resolritter** [comment] 2020-07-19 01:09
According to my findings so far, the main culprit is not the amount of nodes, nor the rendering code for formatting the graph's output, but the fact that diffs are computed upfront - this shouldn't be needed if `g:mundo_inline_undo` is `false`, but even when it's `true`, it should only be computed for the currently visible nodes. I've left a comment with more details and a suggestion there:

https://github.com/simnalamburt/vim-mundo/issues/14#issuecomment-660565181

If that comment doesn't pick up activity then I'm planning to file a new issue. @simnalamburt you mention in the [further plans](https://github.com/simnalamburt/vim-mundo#whats-your-further-plan) that making this plugin faster is a goal, so I'd appreciate if you could opinion on the ideas I posted in that comment.

**Comment by simnalamburt** [comment] 2020-07-19 05:08
Thanks for the report @eyalk5, @resolritter! Looks like vim-mundo is performing unnecessary calculation during startup. I don't have enough time to fix this issue for right now, but I'll try to make some spare time within this month. 😢 

Looks like this issue is duplicate of #14, I'll close this issue and continue the conversation overthere to consolidate information into one.

**Closed by simnalamburt** 2020-07-19 05:08 UTC
