### ISSUE TITLE
differences between undotree

### ISSUE THREAD

**Issue by nhooyr** [simnalamburt/vim-mundo#50] opened 2017-01-01 09:12 UTC
What are the differences between this and https://github.com/mbbill/undotree ?

Also, `g:mundo_inline_graph ` and `g:mundo_help ` appear to do nothing.

**Comment by dsummersl** [comment] 2017-01-01 15:04
On the face of it points 1, 4, 6 appear to still be true in https://github.com/mbbill/undotree#alternatives: this plugin uses python under the hood, it doesn't have a way to toggle timestamps (they are always relative), and it doesn't itself modify the undo history in any way.

I haven't tried this plugin so I can't comment on what it does comprehensively. But I'd point out some of mundo's more obvious differences:

1. the ability to see a simple one line undo in the tree (than you for pointing out the `g:mundo_inline_graph` not working - there was a ticket open for this that I'd neglected to merge (now merged). The setting is actually `g:mundo_inline_undo`.)
2. The tree shows you when files were saved.
3. You can diff any point in the tree with your current file (ie, `:vert diffsplit`).

WRT `g:mundo_help` I tried it this morning and it does appear to work, although I think our docs could be clearer - it toggles the visibility of the help text you see in the mundo tree window. But you can always use the `?` key to expand/close the help text. The help text make it sound like you can permanently disable help, which isn't the case.

**Closed by dsummersl** 2017-01-01 15:04 UTC

**Comment by nhooyr** [comment] 2017-01-01 15:07
@dsummersl btw for me, it looks like `g:mundo_help ==# 0` by default, contrary to what the docs say. that's why I thought it did nothing.

**Comment by nhooyr** [comment] 2017-01-01 15:09
While I prefer the UX of this plugin, undotree was surprisingly faster, at least in terms of opening the window. With a long undo history, this plugin freezes for about a second or so. It's not a big problem, but is there anything that can be done?

**Comment by dsummersl** [comment] 2017-01-01 15:12
@nhooyr could you proof my help text change? https://github.com/simnalamburt/vim-mundo/pull/51/commits/c971edcf48afbce474b36c823c5ebd5a86d8a3b8

Could you give me a sense of how many undos cause it to freeze, how big the file is? I'd love to address the issue if I can reproduce it.

**Comment by nhooyr** [comment] 2017-01-01 15:16
28 line file, 800ish undos.

https://dropbox.aubble.com/main.go

https://dropbox.aubble.com/%25Users%25nhooyr%25code%25gopath%25src%25github.com%25nhooyr%25playground%25main.go

**Comment by nhooyr** [comment] 2017-01-01 15:19
It's only when loading the tree for the first time, after that it is fast.

**Comment by simnalamburt** [comment] 2017-01-01 15:19
@nhooyr Thanks for your help. I did recognize that there is a performance issue with vim-mundo from a long time ago, but there weren't many spare time for me to work on vim-mundo.

**Comment by simnalamburt** [comment] 2017-01-01 15:20
Personally I'm planning to remake this plugin with rust language.

**Comment by nhooyr** [comment] 2017-01-01 15:21
That's cool, take your time and do it in Rust. That would mean it would be a neovim remote plugin right?

**Comment by simnalamburt** [comment] 2017-01-01 15:24
@nhooyr I hope so, but I'm not sure for right now since I've never made neovim remote plugin before.

By the way thank you for pointing out that documentation problem. That documentation is highly outdated and may have another problem too. I'll update it right away.
